version: 2.1

executors:
  flutter:
    docker:
      - image: chengjo0/cci-flutter-fastlane:latest
jobs:
  test:
    executor: flutter
    steps:
      - checkout
      - run: flutter test

  build:
    executor: flutter
    steps:
      - checkout
      - run: echo "$PLAY_STORE_SIGNING_KEY" | base64 --decode > /tmp/signing-key.jks
      - run: echo "$PLAY_STORE_SIGNING_KEY_INFO" | base64 --decode > android/key.properties
      - run: cd android && fastlane build_android

  release-beta:
    executor: flutter
    steps:
      - checkout
      - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > /tmp/upload-key.txt
      - run: cd android && fastlane release_beta

  release-alpha:
    executor: flutter
    steps:
      - checkout
      - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > /tmp/upload-key.txt
      - run: cd android && fastlane release_alpha

workflows:
  sanity-check:
    jobs:
      - test
      - build

  deploy-beta:
    jobs:
      - test:
          filters:
            branches:
              only:
                - "release/beta"
      - build:
          filters:
            branches:
              only:
                - "release/beta"
      - release-beta:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - "release/beta"

  deploy-alpha:
    jobs:
      - test:
          filters:
            branches:
              only:
                - "release/alpha"
      - build:
          filters:
            branches:
              only:
                - "release/alpha"
      - release-alpha:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - "release/alpha"
