version: 2.1

executors:
  flutter:
    docker:
      - image: chengjo0/cci-flutter-fastlane:latest
jobs:
  test:
    executor: flutter
    steps:
      - checkout
      - run: flutter test

  build:
    executor: flutter
    steps:
      - checkout
      - run: echo "$PLAY_STORE_SIGNING_KEY" | base64 --decode > /tmp/signing-key.jks
      - run: echo "$PLAY_STORE_SIGNING_KEY_INFO" | base64 --decode > android/key.properties
      - run: cd android && fastlane build_android

  release-beta:
    executor: flutter
    steps:
      - checkout
      - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > /tmp/upload-key.txt
      - run: cd android && fastlane release_beta
workflows:
  sanity-check:
    jobs:
      - test
      - build
  deploy-beta:
    jobs:
      - test
      - build
      - release-beta:
          requires:
            - test
            - build
    branches:
      only:
        - "release/beta"
